version: '3'

services:
  db:
    image: postgres
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /road:/app
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: road-condition
    command: [ "python","manage.py", "runserver", "--host=0.0.0.0" ]
    environment:
      - PYTHONUNBUFFERED=0
      - DEBUG=1
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db