"""empty message

Revision ID: 63bdf3691c2c
Revises: d3cb92ff801b
Create Date: 2021-05-28 22:24:50.794095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bdf3691c2c'
down_revision = 'd3cb92ff801b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pit', 'users', ['user_id'], ['id'])
    op.add_column('road', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('road', sa.Column('road_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'road', 'road_group', ['road_group_id'], ['id'])
    op.create_foreign_key(None, 'road', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'road', type_='foreignkey')
    op.drop_constraint(None, 'road', type_='foreignkey')
    op.drop_column('road', 'road_group_id')
    op.drop_column('road', 'user_id')
    op.drop_constraint(None, 'pit', type_='foreignkey')
    op.drop_column('pit', 'user_id')
    op.drop_table('road_group')
    # ### end Alembic commands ###
