"""empty message

Revision ID: d3cb92ff801b
Revises: 32fb8116cb80
Create Date: 2021-05-28 20:49:01.747440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cb92ff801b'
down_revision = '32fb8116cb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('road', sa.Column('x_acc', sa.Float(), nullable=True))
    op.add_column('road', sa.Column('y_acc', sa.Float(), nullable=True))
    op.add_column('road', sa.Column('z_acc', sa.Float(), nullable=True))
    op.add_column('road', sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_creation')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'password')
    op.drop_column('road', 'date_creation')
    op.drop_column('road', 'z_acc')
    op.drop_column('road', 'y_acc')
    op.drop_column('road', 'x_acc')
    op.drop_table('pit')
    # ### end Alembic commands ###
